# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd4a3faa45c88d81eaecd02957eaef63758b32fe09242708051154c9ae0532b015965fc793d8296abc98620c99407bf01613b8647b008a4f8f3df4126062a86

test:
  secret_key_base: 103e5ed05a8d7eee0050c00b22bc4821cc8329dd92da1713c8c7d568538bc74a6ea033339f5859055305a3b48feb628f54102634dd2d2415f9fec2638036efc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
